services:
  mariadb:
    build: .
    container_name: Basdat
    restart: unless-stopped
    command: --event-scheduler=ON
    ports:
      - "3307:3306"
    volumes:
      - tubes_basdat:/var/lib/mysql

volumes:
  tubes_basdat: